### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by Ensaia** [tobischulz/laravel-vue-spa-boilerplate#8]
i am getting CSRF token mismatch while registration?

**Comment by tobischulz** [comment]
Did you set up the .env correctly? Have a look at the last issue #5. Maybe this helps. 

Will close this issue caused by age of the issue. Feel free to open up a new issue.

**Comment by Ensaia** [comment]
i did all settings as you mentioned but it didn't work for me so i tried to add localhost:8000 to sanctum file in config folder so it did the job well.
